// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skinet.Api.Data;

#nullable disable

namespace Skinet.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331055420_FixAllImages")]
    partial class FixAllImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skinet.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("text");

                    b.Property<string>("ProcessedWebhookEventId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Skinet.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Skinet.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "PetalCo",
                            Category = "Fresh Bouquets",
                            Description = "A dreamy arrangement of soft blush peonies, perfect for gifting or brightening any space.",
                            ImageUrl = "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80",
                            Name = "Blush Peony Bouquet",
                            Price = 48.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 2,
                            Brand = "BloomHaus",
                            Category = "Fresh Bouquets",
                            Description = "Twelve long-stem lavender roses wrapped in soft kraft paper with a satin ribbon.",
                            ImageUrl = "https://images.unsplash.com/photo-1548094990-c16ca90f1f0d?auto=format&fit=crop&w=800&q=80",
                            Name = "Lavender Rose Bundle",
                            Price = 54.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 3,
                            Brand = "PetalCo",
                            Category = "Fresh Bouquets",
                            Description = "A cheerful mix of pink, peach and cream tulips bundled in a cloud of baby's breath.",
                            ImageUrl = "https://images.unsplash.com/photo-1462275646964-a0e3386b89fa?auto=format&fit=crop&w=800&q=80",
                            Name = "Pastel Tulip Bunch",
                            Price = 34.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 4,
                            Brand = "BloomHaus",
                            Category = "Fresh Bouquets",
                            Description = "Pure white oriental lilies arranged with eucalyptus for a clean, minimal look.",
                            ImageUrl = "https://images.unsplash.com/photo-1496062031456-07b8f162a322?auto=format&fit=crop&w=800&q=80",
                            Name = "White Lily Elegance",
                            Price = 62.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 5,
                            Brand = "FleurJoy",
                            Category = "Fresh Bouquets",
                            Description = "A lush mixed garden bouquet with roses, ranunculus, and sweet-smelling freesia.",
                            ImageUrl = "https://images.unsplash.com/photo-1455582916367-25f75bfc6710?auto=format&fit=crop&w=800&q=80",
                            Name = "Garden Rose Medley",
                            Price = 58.99m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 6,
                            Brand = "PetalCo",
                            Category = "Fresh Bouquets",
                            Description = "Bright sunflowers paired with delicate chamomile for a warm, cottagecore feel.",
                            ImageUrl = "https://images.unsplash.com/photo-1470509037663-253d462dc0f9?auto=format&fit=crop&w=800&q=80",
                            Name = "Sunflower & Chamomile Bunch",
                            Price = 38.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 7,
                            Brand = "FleurJoy",
                            Category = "Fresh Bouquets",
                            Description = "Fluffy pink carnations gathered in a soft cloud-like bouquet, tied with a pastel bow.",
                            ImageUrl = "https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?auto=format&fit=crop&w=800&q=80",
                            Name = "Pink Carnation Cloud",
                            Price = 29.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 8,
                            Brand = "BloomHaus",
                            Category = "Fresh Bouquets",
                            Description = "Voluminous baby blue hydrangeas, each head full and lush — a statement piece for any room.",
                            ImageUrl = "https://images.unsplash.com/photo-1591886960571-74d43a9d4166?auto=format&fit=crop&w=800&q=80",
                            Name = "Baby Blue Hydrangea Bunch",
                            Price = 44.99m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 9,
                            Brand = "PetalCo",
                            Category = "Fresh Bouquets",
                            Description = "Soft peach ranunculus wrapped in vellum paper with a gold twine tie.",
                            ImageUrl = "https://images.unsplash.com/photo-1444930694458-01babf71870c?auto=format&fit=crop&w=800&q=80",
                            Name = "Peach Ranunculus Wrap",
                            Price = 42.99m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 10,
                            Brand = "FleurJoy",
                            Category = "Fresh Bouquets",
                            Description = "A hand-tied posy of seasonal wildflowers, fresh from the meadow to your doorstep.",
                            ImageUrl = "https://images.unsplash.com/photo-1468327768560-75b778cbb551?auto=format&fit=crop&w=800&q=80",
                            Name = "Wildflower Meadow Posy",
                            Price = 27.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 11,
                            Brand = "BloomHaus",
                            Category = "Fresh Bouquets",
                            Description = "Delicate cherry blossom branches arranged with soft pink filler flowers.",
                            ImageUrl = "https://images.unsplash.com/photo-1522748906645-95d8adfd52c7?auto=format&fit=crop&w=800&q=80",
                            Name = "Cherry Blossom Spray",
                            Price = 52.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 12,
                            Brand = "PetalCo",
                            Category = "Fresh Bouquets",
                            Description = "Fresh white daisies with mint green leaves — clean, simple and so cheerful.",
                            ImageUrl = "https://images.unsplash.com/photo-1502977249166-824b3a8a4d6d?auto=format&fit=crop&w=800&q=80",
                            Name = "Mint & White Daisy Bundle",
                            Price = 24.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 13,
                            Brand = "FleurJoy",
                            Category = "Fresh Bouquets",
                            Description = "Pastel sweet peas in blush, lavender and cream, lightly fragrant and airy.",
                            ImageUrl = "https://images.unsplash.com/photo-1487530811015-780bfb1fef1a?auto=format&fit=crop&w=800&q=80",
                            Name = "Sweet Pea Soft Bunch",
                            Price = 36.99m,
                            StockQuantity = 32
                        },
                        new
                        {
                            Id = 14,
                            Brand = "EverBloom",
                            Category = "Dried & Preserved",
                            Description = "Fluffy natural pampas grass stems — perfect for vases and boho home decor.",
                            ImageUrl = "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=800&q=80",
                            Name = "Dried Pampas Grass Bunch",
                            Price = 32.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 15,
                            Brand = "ForeverPetal",
                            Category = "Dried & Preserved",
                            Description = "A single preserved rose under a glass dome — lasts up to 3 years without water.",
                            ImageUrl = "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80",
                            Name = "Preserved Rose Dome",
                            Price = 69.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 16,
                            Brand = "EverBloom",
                            Category = "Dried & Preserved",
                            Description = "Fragrant dried lavender stems tied with twine — aromatherapy meets home decor.",
                            ImageUrl = "https://images.unsplash.com/photo-1499578124509-1611b77778e8?auto=format&fit=crop&w=800&q=80",
                            Name = "Dried Lavender Bundle",
                            Price = 18.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 17,
                            Brand = "ForeverPetal",
                            Category = "Dried & Preserved",
                            Description = "A handcrafted wreath of dried blush peonies and eucalyptus for your front door.",
                            ImageUrl = "https://images.unsplash.com/photo-1559181567-c3190900f8b5?auto=format&fit=crop&w=800&q=80",
                            Name = "Blush Dried Peony Wreath",
                            Price = 84.99m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 18,
                            Brand = "EverBloom",
                            Category = "Dried & Preserved",
                            Description = "Bright strawflowers in pink, peach and cream — dried to perfection and long-lasting.",
                            ImageUrl = "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=800&q=80",
                            Name = "Dried Strawflower Bouquet",
                            Price = 26.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 19,
                            Brand = "ForeverPetal",
                            Category = "Dried & Preserved",
                            Description = "Delicate preserved baby's breath in a minimal glass jar — effortlessly cute.",
                            ImageUrl = "https://images.unsplash.com/photo-1508610048659-a06b669e3321?auto=format&fit=crop&w=800&q=80",
                            Name = "Preserved Baby's Breath Jar",
                            Price = 22.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 20,
                            Brand = "EverBloom",
                            Category = "Dried & Preserved",
                            Description = "Soft dried cotton stems for minimalist floral arrangements or boho styling.",
                            ImageUrl = "https://images.unsplash.com/photo-1490750967868-88df5691cc08?auto=format&fit=crop&w=800&q=80",
                            Name = "Dried Cotton Stem Bundle",
                            Price = 21.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 21,
                            Brand = "ForeverPetal",
                            Category = "Dried & Preserved",
                            Description = "Preserved pink hydrangeas in a keepsake gift box — ready to display forever.",
                            ImageUrl = "https://images.unsplash.com/photo-1560717845-968823efbee1?auto=format&fit=crop&w=800&q=80",
                            Name = "Pink Preserved Hydrangea Box",
                            Price = 54.99m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 22,
                            Brand = "EverBloom",
                            Category = "Dried & Preserved",
                            Description = "Fluffy bunny tail grass stems — impossibly soft and adorable in any arrangement.",
                            ImageUrl = "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=800&q=80",
                            Name = "Dried Bunny Tail Grass",
                            Price = 16.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 23,
                            Brand = "ForeverPetal",
                            Category = "Dried & Preserved",
                            Description = "Real pressed roses and wildflowers in a gold-frame — a piece of living art.",
                            ImageUrl = "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?auto=format&fit=crop&w=800&q=80",
                            Name = "Vintage Rose Pressed Frame",
                            Price = 78.99m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 24,
                            Brand = "EverBloom",
                            Category = "Dried & Preserved",
                            Description = "Silvery lunaria (honesty plant) stems that catch the light beautifully.",
                            ImageUrl = "https://images.unsplash.com/photo-1471086569966-db3eebc25a59?auto=format&fit=crop&w=800&q=80",
                            Name = "Dried Lunaria Moon Stems",
                            Price = 19.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 25,
                            Brand = "ForeverPetal",
                            Category = "Dried & Preserved",
                            Description = "A curated mix of dried blush and cream blooms — romantic, timeless and zero maintenance.",
                            ImageUrl = "https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=800&q=80",
                            Name = "Blush & Cream Dried Bouquet",
                            Price = 44.99m,
                            StockQuantity = 28
                        });
                });

            modelBuilder.Entity("Skinet.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Skinet.Api.Models.Order", b =>
                {
                    b.HasOne("Skinet.Api.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skinet.Api.Models.OrderItem", b =>
                {
                    b.HasOne("Skinet.Api.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skinet.Api.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Skinet.Api.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Skinet.Api.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Skinet.Api.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
